//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CenterMMibDbViewer.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class header
    {
        public string header1 { get; set; }
        public string value { get; set; }
        public Nullable<long> packet_suid { get; set; }
    }
}
