//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CenterMMibDbViewer.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class in_packet
    {
        public long suid { get; set; }
        public string sender { get; set; }
        public string meta { get; set; }
        public Nullable<System.DateTime> received { get; set; }
        public Nullable<System.DateTime> processed { get; set; }
        public string secrecy { get; set; }
    }
}
