//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CenterMMibDbViewer.Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MibDbContext : DbContext
    {
        public MibDbContext()
            : base("name=MibDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<in_packet> in_packet { get; set; }
        public virtual DbSet<out_packet> out_packet { get; set; }
        public virtual DbSet<header> headers { get; set; }
        public virtual DbSet<upd_history> upd_history { get; set; }
    }
}
