//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CenterMMibDbViewer.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class out_packet
    {
        public long suid { get; set; }
        public System.Guid msa_id { get; set; }
        public System.DateTime created { get; set; }
        public Nullable<System.Guid> mib_id { get; set; }
        public string meta { get; set; }
        public Nullable<int> priority { get; set; }
        public string secrecy { get; set; }
    }
}
