//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CenterMMibDbViewer.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class upd_history
    {
        public long suid { get; set; }
        public string db_name { get; set; }
        public string upd_name { get; set; }
        public bool is_comitted { get; set; }
        public System.DateTime commit_date { get; set; }
    }
}
